convert/urls.py
from django.urls import path

from .views import convert, download_archive, view_convert_result

app_name = "convert"
urlpatterns = [
    path("", convert, name="convert"),
    path("result/<uuid:task_id>", view_convert_result, name="view-convert-result"),
    path("download/<uuid:task_id>", download_archive, name="download-archive"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("notion-to-focalboard/", include("convert.urls")),
]

convert/models.py
import os
import uuid

from django.conf import settings
from django.db import models


class ConvertTask(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    notion_export = models.FileField(upload_to="notion_export")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    error_msg = models.TextField(max_length=1000, blank=True)

    class State(models.TextChoices):
        PENDING = "pending", "Pending"
        RUNNING = "running", "Running"
        COMPLETED = "completed", "Completed"
        FAILED = "failed", "Failed"

    state = models.CharField(
        max_length=10,
        choices=State.choices,
        default=State.PENDING,
    )

    def __str__(self):
        return f"{self.id}: {self.state}"

    def get_archive_name(self):
        return os.path.splitext(os.path.basename(self.notion_export.path))[0]

    def get_result_path(self):
        return settings.MEDIA_ROOT / "result" / f"{self.id}.boardarchive"

convert/views.py
from django import forms
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .models import ConvertTask


class ConvertForm(forms.ModelForm):
    class Meta:
        model = ConvertTask
        fields = ["notion_export"]


def convert(request):
    if request.method == "POST":
        form = ConvertForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("convert:view-convert-result", task_id=form.instance.id)
    else:
        form = ConvertForm()
    return render(request, "convert/convert.html", {"form": form})


def view_convert_result(request, task_id):
    task = get_object_or_404(ConvertTask, id=task_id)
    return render(request, "convert/result.html", {"task": task})


def download_archive(request, task_id):
    task = get_object_or_404(ConvertTask, id=task_id)
    try:
        archive = open(task.get_result_path(), "rb")
    except FileNotFoundError:
        return HttpResponse("File not found.", status=404)
    response = StreamingHttpResponse(archive)
    response[
        "Content-Disposition"
    ] = f"attachment; filename={task.get_archive_name()}.boardarchive"
    return response

convert/templates/convert/base.html
<html>
<head>
    <title>Notion to Focalboard</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Vazirmatn:wght@100;400&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: Roboto;
            background: #f5f8fa;
        }
        .container {
            max-width: 40em;
            margin: 3em auto;
            
        }
        .card {
            background: #fff;
            padding: 1.5em;
            border-radius: 1em;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        #copyright {
            text-align: center;
            margin: 1em 0;
            font-size: 0.8em;
            color: #999;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="card">
            {% block body %}
            {% endblock %}
        </div>
        <div id="copyright">
        Quera
        </div>
    </div>
</body>

convert/templates/convert/convert.html
{% extends 'convert/base.html' %}

{% block body%}
    <h1 style="margin-top: 0">Notion to Focalboard</h1>
    <p>Convert Notion export to Focalboard archive using this form.</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="submit" value="Upload">
    </form>
{% endblock %}

convert/templates/convert/result.html
{% extends 'convert/base.html' %}

{% block body %}
    Convert Status: <b>{{ task.get_state_display }}</b>
    {% if task.state == task.State.FAILED %}
        <pre>{{ task.error_msg }}</pre>
    {% elif task.state == task.State.COMPLETED %}
        <p>
            <a href="{% url 'convert:download-archive' task.id %}">Download the result</a>
            <br>
            File will be deleted after 24 hours.
        </p>
    {% else %}
        <p>Please wait...</p>
        <script>
            (function() {
                const DELAY = 5000;
                let ttl = 20;
                function reload() {
                    ttl--;
                    window.location.reload();
                    if (ttl > 0) {
                        setTimeout(reload, DELAY);
                    }
                }
                setTimeout(reload, DELAY);
            })();
        </script>
    {% endif %}
    <div><a href="{% url 'convert:convert' %}">Convert another file</a></div>
{% endblock %}